<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaktabTaha.Domain\MaktabTaha.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO%27s\caseDesc\Create\" />
    <Folder Include="DTO%27s\caseDesc\List\" />
    <Folder Include="DTO%27s\caseDesc\Update\" />
    <Folder Include="Features\baseEntities\area\Command\Create\" />
    <Folder Include="Features\baseEntities\area\Command\Delete\" />
    <Folder Include="Features\baseEntities\area\Command\Update\" />
    <Folder Include="Features\baseEntities\area\Query\Single\" />
    <Folder Include="Features\baseEntities\bank\Command\Create\" />
    <Folder Include="Features\baseEntities\bank\Command\Delete\" />
    <Folder Include="Features\baseEntities\bank\Command\Update\" />
    <Folder Include="Features\baseEntities\bank\Query\Single\" />
    <Folder Include="Features\baseEntities\caseStage\Command\Create\" />
    <Folder Include="Features\baseEntities\caseStage\Command\Delete\" />
    <Folder Include="Features\baseEntities\caseStage\Command\Update\" />
    <Folder Include="Features\baseEntities\caseStage\Query\Single\" />
    <Folder Include="Features\baseEntities\caseType\Command\Create\" />
    <Folder Include="Features\baseEntities\caseType\Command\Delete\" />
    <Folder Include="Features\baseEntities\caseType\Command\Update\" />
    <Folder Include="Features\baseEntities\caseType\Query\Single\" />
    <Folder Include="Features\baseEntities\charityMainRole\Command\Create\" />
    <Folder Include="Features\baseEntities\charityMainRole\Command\Delete\" />
    <Folder Include="Features\baseEntities\charityMainRole\Command\Update\" />
    <Folder Include="Features\baseEntities\charityMainRole\Query\Single\" />
    <Folder Include="Features\baseEntities\city\Command\Create\" />
    <Folder Include="Features\baseEntities\city\Command\Delete\" />
    <Folder Include="Features\baseEntities\city\Command\Update\" />
    <Folder Include="Features\baseEntities\city\Query\Single\" />
    <Folder Include="Features\baseEntities\dependancyStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\dependancyStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\dependancyStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\dependancyStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\educationLevel\Command\Create\" />
    <Folder Include="Features\baseEntities\educationLevel\Command\Delete\" />
    <Folder Include="Features\baseEntities\educationLevel\Command\Update\" />
    <Folder Include="Features\baseEntities\educationLevel\Query\Single\" />
    <Folder Include="Features\baseEntities\educationStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\educationStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\educationStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\educationStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\employmentStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\employmentStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\employmentStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\employmentStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\gender\Command\Create\" />
    <Folder Include="Features\baseEntities\gender\Command\Delete\" />
    <Folder Include="Features\baseEntities\gender\Command\Update\" />
    <Folder Include="Features\baseEntities\gender\Query\Single\" />
    <Folder Include="Features\baseEntities\goodWorkType\Command\Create\" />
    <Folder Include="Features\baseEntities\goodWorkType\Command\Delete\" />
    <Folder Include="Features\baseEntities\goodWorkType\Command\Update\" />
    <Folder Include="Features\baseEntities\goodWorkType\Query\Single\" />
    <Folder Include="Features\baseEntities\houeHeadStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\houeHeadStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\houeHeadStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\houeHeadStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\housingStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\housingStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\housingStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\housingStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\job\Command\Create\" />
    <Folder Include="Features\baseEntities\job\Command\Delete\" />
    <Folder Include="Features\baseEntities\job\Command\Update\" />
    <Folder Include="Features\baseEntities\job\Query\Single\" />
    <Folder Include="Features\baseEntities\maritalStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\maritalStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\maritalStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\maritalStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\nationality\Command\Create\" />
    <Folder Include="Features\baseEntities\nationality\Command\Delete\" />
    <Folder Include="Features\baseEntities\nationality\Command\Update\" />
    <Folder Include="Features\baseEntities\nationality\Query\Single\" />
    <Folder Include="Features\baseEntities\orphanStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\orphanStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\orphanStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\orphanStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\physicalStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\physicalStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\physicalStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\physicalStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\privatenessStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\privatenessStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\privatenessStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\privatenessStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\province\Command\Create\" />
    <Folder Include="Features\baseEntities\province\Command\Delete\" />
    <Folder Include="Features\baseEntities\province\Command\Update\" />
    <Folder Include="Features\baseEntities\province\Query\Single\" />
    <Folder Include="Features\baseEntities\relation\Command\Create\" />
    <Folder Include="Features\baseEntities\relation\Command\Delete\" />
    <Folder Include="Features\baseEntities\relation\Command\Update\" />
    <Folder Include="Features\baseEntities\relation\Query\Single\" />
    <Folder Include="Features\baseEntities\religon\Command\Create\" />
    <Folder Include="Features\baseEntities\religon\Command\Delete\" />
    <Folder Include="Features\baseEntities\religon\Command\Update\" />
    <Folder Include="Features\baseEntities\religon\Query\Single\" />
    <Folder Include="Features\baseEntities\requestStatus\Command\Create\" />
    <Folder Include="Features\baseEntities\requestStatus\Command\Delete\" />
    <Folder Include="Features\baseEntities\requestStatus\Command\Update\" />
    <Folder Include="Features\baseEntities\requestStatus\Query\Single\" />
    <Folder Include="Features\baseEntities\requestType\Command\Create\" />
    <Folder Include="Features\baseEntities\requestType\Command\Delete\" />
    <Folder Include="Features\baseEntities\requestType\Command\Update\" />
    <Folder Include="Features\baseEntities\requestType\Query\Single\" />
    <Folder Include="Features\baseEntities\skill\Command\Create\" />
    <Folder Include="Features\baseEntities\skill\Command\Delete\" />
    <Folder Include="Features\baseEntities\skill\Command\Update\" />
    <Folder Include="Features\baseEntities\skill\Query\Single\" />
    <Folder Include="Features\baseEntities\unemploymentReason\Command\Create\" />
    <Folder Include="Features\baseEntities\unemploymentReason\Command\Delete\" />
    <Folder Include="Features\baseEntities\unemploymentReason\Command\Update\" />
    <Folder Include="Features\baseEntities\unemploymentReason\Query\Single\" />
  </ItemGroup>

</Project>
